import type { Project } from "@/lib/db";
import { upsertProjectFile } from "@/lib/db";

function slugify(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return slug || "my_mod";
}

/** Scaffolds a minimal Fabric mod (mod metadata + one example class) for a freshly created project. */
export function scaffoldFabricProject(project: Project): void {
  const modId = slugify(project.name);
  const packagePath = `com/example/${modId}`;
  const className = "ExampleMod";

  const fabricModJson = {
    schemaVersion: 1,
    id: modId,
    version: "1.0.0",
    name: project.name,
    description: `${project.name} — generated by Minecraft Version Compiler`,
    authors: [],
    contact: {},
    license: "MIT",
    icon: "assets/" + modId + "/icon.png",
    environment: "*",
    entrypoints: {
      main: [`com.example.${modId}.${className}`],
    },
    depends: {
      fabricloader: `>=${project.fabricLoaderVersion}`,
      minecraft: `~${project.minecraftVersion}`,
      java: ">=21",
    },
  };

  const exampleModJava = `package com.example.${modId};

import net.fabricmc.api.ModInitializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ${className} implements ModInitializer {
    public static final String MOD_ID = "${modId}";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        LOGGER.info("Initializing {}", MOD_ID);
    }
}
`;

  upsertProjectFile({
    projectId: project.id,
    path: "src/main/resources/fabric.mod.json",
    content: JSON.stringify(fabricModJson, null, 2) + "\n",
    origin: "USER_AUTHORED",
  });

  upsertProjectFile({
    projectId: project.id,
    path: `src/main/java/${packagePath}/${className}.java`,
    content: exampleModJava,
    origin: "USER_AUTHORED",
  });
}
